chia_exe: ./chia.bin
chia_path: /chia-gigahorse-farmer/
chia_t: 40041327
cp_dir:
- /chia-gigahorse-farmer
data_collect: /chia-gigahorse-farmer/data_collect/
disk_list:
- []
- - '1255'
  - '0773'
  - '2358'
- - '63'
  - '65'
  - '65'
host_list:
- http://192.168.0.73:5000/upgrade
mount_path: /home/z/z_share
password: z
plots_dir: /261398126/
root: z
share_link: //192.168.0.63/z_share/
share_password: z
share_username: z
