# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 't1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(836, 761)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.tab_3)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setMidLineWidth(1)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.widget_3)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 13, 67, 17))
        self.label_5.setObjectName("label_5")
        self.lineEdit_disk = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_disk.setGeometry(QtCore.QRect(80, 10, 113, 25))
        self.lineEdit_disk.setObjectName("lineEdit_disk")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(220, 13, 61, 17))
        self.label_6.setObjectName("label_6")
        self.lineEdit_plot = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_plot.setGeometry(QtCore.QRect(280, 10, 113, 25))
        self.lineEdit_plot.setObjectName("lineEdit_plot")
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.widget_3)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_front = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_front.setInputMask("")
        self.lineEdit_front.setObjectName("lineEdit_front")
        self.gridLayout_11.addWidget(self.lineEdit_front, 0, 2, 1, 1)
        self.pushButton_seach = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_seach.setObjectName("pushButton_seach")
        self.gridLayout_11.addWidget(self.pushButton_seach, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_11.addWidget(self.label_7, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_11.addWidget(self.checkBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.widget = QtWidgets.QWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget.setToolTipDuration(0)
        self.widget.setObjectName("widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_reboot = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_reboot.setObjectName("pushButton_reboot")
        self.gridLayout_3.addWidget(self.pushButton_reboot, 3, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.groupBox)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_6 = QtWidgets.QWidget(self.widget_4)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label = QtWidgets.QLabel(self.widget_6)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 2, 1, 1)
        self.lineEdit_add = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_add.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_add.setText("")
        self.lineEdit_add.setObjectName("lineEdit_add")
        self.gridLayout_7.addWidget(self.lineEdit_add, 0, 3, 1, 1)
        self.pushButton_label = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_label.setMaximumSize(QtCore.QSize(65, 16777215))
        self.pushButton_label.setObjectName("pushButton_label")
        self.gridLayout_7.addWidget(self.pushButton_label, 0, 8, 1, 1)
        self.lineEdit_old = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_old.setObjectName("lineEdit_old")
        self.gridLayout_7.addWidget(self.lineEdit_old, 0, 0, 1, 1)
        self.lineEdit_new = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_new.setText("")
        self.lineEdit_new.setObjectName("lineEdit_new")
        self.gridLayout_7.addWidget(self.lineEdit_new, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_6)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 4, 1, 1)
        self.gridLayout_2.addWidget(self.widget_6, 0, 2, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_label_2 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_label_2.setObjectName("pushButton_label_2")
        self.gridLayout_4.addWidget(self.pushButton_label_2, 1, 1, 1, 1)
        self.lineEdit_ad = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_ad.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_ad.setText("")
        self.lineEdit_ad.setObjectName("lineEdit_ad")
        self.gridLayout_4.addWidget(self.lineEdit_ad, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_5, 1, 2, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout_2.addWidget(self.pushButton_save, 2, 2, 1, 1)
        self.gridLayout_3.addWidget(self.widget_4, 8, 0, 1, 1)
        self.progressBar_reboot = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_reboot.setProperty("value", 24)
        self.progressBar_reboot.setObjectName("progressBar_reboot")
        self.gridLayout_3.addWidget(self.progressBar_reboot, 4, 0, 1, 1)
        self.pushButton_mount = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_mount.setObjectName("pushButton_mount")
        self.gridLayout_3.addWidget(self.pushButton_mount, 6, 0, 1, 1)
        self.textBrowser_msg = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_msg.setObjectName("textBrowser_msg")
        self.gridLayout_3.addWidget(self.textBrowser_msg, 11, 0, 1, 1)
        self.pushButton_HARVESTER = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_HARVESTER.setObjectName("pushButton_HARVESTER")
        self.gridLayout_3.addWidget(self.pushButton_HARVESTER, 5, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.widget)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setHorizontalSpacing(4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_8.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_farm = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_farm.setObjectName("pushButton_farm")
        self.horizontalLayout.addWidget(self.pushButton_farm)
        self.pushButton_chia = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_chia.setObjectName("pushButton_chia")
        self.horizontalLayout.addWidget(self.pushButton_chia)
        self.pushButton_nvidia = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_nvidia.setObjectName("pushButton_nvidia")
        self.horizontalLayout.addWidget(self.pushButton_nvidia)
        self.pushButton_del = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_del.setObjectName("pushButton_del")
        self.horizontalLayout.addWidget(self.pushButton_del)
        self.pushButton_upgrade = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_upgrade.setObjectName("pushButton_upgrade")
        self.horizontalLayout.addWidget(self.pushButton_upgrade)
        self.gridLayout_8.addWidget(self.widget_2, 0, 0, 1, 1)
        self.gridLayout_8.setRowStretch(0, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tableWidget_disk = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_disk.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_disk.setObjectName("tableWidget_disk")
        self.tableWidget_disk.setColumnCount(3)
        self.tableWidget_disk.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_disk.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_disk.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_disk.setHorizontalHeaderItem(2, item)
        self.tableWidget_disk.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget_disk.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_disk.verticalHeader().setStretchLastSection(False)
        self.gridLayout_10.addWidget(self.tableWidget_disk, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "chia 管理器"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "硬盘名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "P图数量"))
        self.label_5.setText(_translate("MainWindow", "硬盘数量："))
        self.label_6.setText(_translate("MainWindow", "图总数："))
        self.lineEdit_front.setText(_translate("MainWindow", "~"))
        self.lineEdit_front.setPlaceholderText(_translate("MainWindow", "~"))
        self.pushButton_seach.setText(_translate("MainWindow", "搜索"))
        self.label_7.setText(_translate("MainWindow", "前载："))
        self.checkBox.setText(_translate("MainWindow", "全选"))
        self.groupBox.setTitle(_translate("MainWindow", "功能"))
        self.pushButton_reboot.setText(_translate("MainWindow", "重启chia服务"))
        self.label.setText(_translate("MainWindow", ">"))
        self.pushButton_label.setText(_translate("MainWindow", "更改卷标"))
        self.label_2.setText(_translate("MainWindow", "-"))
        self.pushButton_label_2.setText(_translate("MainWindow", "批量加前载修改卷标"))
        self.pushButton_save.setText(_translate("MainWindow", "保存硬盘列表"))
        self.pushButton_mount.setText(_translate("MainWindow", "启动扫描挂载硬盘"))
        self.pushButton_HARVESTER.setText(_translate("MainWindow", "获取收割机ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "硬盘信息"))
        self.pushButton_farm.setText(_translate("MainWindow", "耕种状态"))
        self.pushButton_chia.setText(_translate("MainWindow", "区块链状态"))
        self.pushButton_nvidia.setText(_translate("MainWindow", "中文翻译"))
        self.pushButton_del.setText(_translate("MainWindow", "清除坏图"))
        self.pushButton_upgrade.setText(_translate("MainWindow", "一键升级"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "查看信息"))
        item = self.tableWidget_disk.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "硬盘"))
        item = self.tableWidget_disk.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "事件"))
        item = self.tableWidget_disk.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "时间"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "硬盘提示"))
